### PR TITLE
Update Dotnet, convert to async action methods, update nuget packages

### PR DESCRIPTION
**Pull request by parthchopra**
Upgrade MVCMovie Project to the latest dotnet (4.8) #239
Convert action methods to async
Upgrade nuget packages

@Rick-Anderson  edit:
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/getting-started?branch=pr-en-us-242)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@parthchopra  I haven't done .NET 4.x in so long I forgot how to download the NuGet packages so I can compile the project. The NuGet package manager was unable to update the project.

**Comment by Rick-Anderson** [comment]
image

**Comment by parthchopra** [comment]
Hi Rick, I ran into this same issue and it turned out the nuget restore fails for solutions with very long paths. What I had to do is following

1. Allow long paths in windows
https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path

2. net use x: path\Of\your\repo\aspnet\mvc\overview\getting-started\introduction\sample\MvcMovie

Then start open the solution like
3. start x:\MvcMovie\MvcMoview\MvcMoview.sln

Then you will be able to restore packages. I couldn't find a better approach.

**Comment by Rick-Anderson** [comment]
I get this error

C:\wrk\AspNetDocs\aspnet\mvc\overview\getting-started\introduction\sample\MvcMovie\MvcMovie>net use C:\wrk\AspNetDocs\aspnet\mvc\overview\getting-started\introduction\sample\MvcMovie\MvcMovie
System error 67 has occurred.

The network name cannot be found.

**Comment by Rick-Anderson** [comment]
@gewarren Have you seen this problem with the current VS19?

**Comment by gewarren** [comment]
> @gewarren Have you seen this problem with the current VS19?

No I haven't, and I [don't see anything on Developer Community](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=nuget+restore+fails+for+solutions+with+long+file+paths). You could log the issue using Report a Problem.

**Comment by Rick-Anderson** [comment]
I created a new project and copied the relevant files over. I've got it running now.

@parthchopra I made a big mistake when I wrote this adding Identity. It's not used and generates millions of extra files.

**Comment by Rick-Anderson** [comment]
@parthchopra  this code doesn't match the document. Did you use the scaffolder to generate the code?

**Comment by Rick-Anderson** [comment]
@parthchopra  click on show all check/details. You need to delete all the readme.MD files in the scripts folder.

**Comment by parthchopra** [comment]
Hi @Rick-Anderson 
1. I'm able to use the net use command and successfully build the solution. Note: I'm using VS2019 and have the nuget errors with long paths in the doc solution.
image

2. Do you want me to create a separate issue to remove identity and all the related files?

3. I updated the documentation (samples and images) where applicable to match the async methods used in the PR. Also updating variable casing to follow the conventions.

4. I'm not sure how the min and map files got in the commit as I did not modify the gitignore file. But I removed those and other readme files in the updates.

5. I just updated the controller to use async methods but I cross checked with scaffolded code and it matches with the PR changes.

**Comment by Rick-Anderson** [comment]
> Do you want me to create a separate issue to remove identity and all the related files?

We can think about doing that in another PR

**Comment by Rick-Anderson** [comment]
@parthchopra  can you remove *aspnet/mvc/overview/getting-started/introduction/sample/MvcMovie/MvcMovie/Content/* from the commit?

**Comment by Rick-Anderson** [comment]
What about removing aspnet/mvc/overview/getting-started/introduction/sample/MvcMovie/MvcMovie/Scripts/ ?

**Comment by Rick-Anderson** [comment]
Ideally we'd remove all the *aspnet/mvc/overview/getting-started/introduction/accessing-your-models-data-from-a-controller/samples/* file and reference all the snippets from the actual code. That's how we do it in https://github.com/aspnet/AspNetCore.Docs

**Comment by parthchopra** [comment]
I updated all the nuget packages which included scripts and css files.
Do you mean identify the scripts are not required and removing them from packages.config?

**Comment by Rick-Anderson** [comment]
> Do you mean identify the scripts are not required and removing them from packages.config?

No, the changed files list is way too big. Still lots of .min and .map files.

**Comment by parthchopra** [comment]
> _models-data-from-a-controller/samples/_ file and reference all the snippets from the actual c
I saw that way after creating the PR. :) 
I can update the PR so we are referencing actual code files.

**Comment by parthchopra** [comment]
> > Do you mean identify the scripts are not required and removing them from packages.config?
> 
> No, the changed files list is way too big. Still lots of .min and .map files.

forgot the min and map files in content I will get rid of them and update the PR.
Let me know if there is anything else

**Comment by parthchopra** [comment]
I tried running the docfx and got an error about missing directory from the repo.

[docfx_errors.txt](https://github.com/aspnet/AspNetDocs/files/3785230/docfx_errors.txt)

**Comment by Rick-Anderson** [comment]
What is authentication included? 
image

**Comment by parthchopra** [comment]
> What is authentication included?
> image
> 
> The instructions don't have you include it. Let's remove the auth stuff.

Hi @Rick-Anderson 
I'm not sure what Auth stuff you are talking about. If you mean in the Account and Manage controllers, all I did was to convert the property getters to use expression syntax.

**Comment by parthchopra** [comment]
> I tried running the docfx and got an error about missing directory from the repo.
> 
> [docfx_errors.txt](https://github.com/aspnet/AspNetDocs/files/3785230/docfx_errors.txt)

Again the issue was long path.
net use command to rescue again. I wish long paths/filenames weren't an issue any more.

**Comment by Rick-Anderson** [comment]
Yes Account/Manage controllers and view directory implement auth.

**Pull request closed without merging**
