### PR TITLE
SFI Images Sev 2 Part 1

### PR DESCRIPTION
**Pull request by wadepickett**
Contriutes to dotnet/aspnetcore.docs#33753

Fixes to SFI images per guidelines.

No images have been removed, only updated.

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
Didn't we delete Real World Cloud Apps, so shouldn't any of its images be deleted too?
For the rest, some have information blanked out that doesn't seem to me to be cause for security concern, but I trust your judgment, so LGTM.

**Comment by wadepickett** [comment]
I will check on real world cloud apps.  Although it would be odd that we deleted it and didn't bother deleting the images and samples at the time that went with it.

**Comment by wadepickett** [comment]
I see what happened. I need to remove Real World Cloud Apps per this issue:
https://github.com/dotnet/AspNetCore.Docs/issues/33742

I will go ahead and leave the fixes in this PR to the images for that they are no longer an issue now as they are due, and then after I get all the images taken care of across the repos that we need to do for this sprint as a priority I will come back to that issue of deleting and  providing redirects.  It is a rather large series with 17 topics.  Thanks.

**Comment by wadepickett** [comment]
I see what happened. I need to remove Real World Cloud Apps per this issue:
https://github.com/dotnet/AspNetCore.Docs/issues/33742

I will go ahead and leave the fixes to the images for that content in here so we can clear out the issues for images now, and then after I get all the images taken care of across the repos that we need to do for this sprint as a priority I will come back to that issue of deleting and  providing redirects.  It is a rather large series with 17 topics.

**Comment by tdykstra** [comment]
> could you point me to an example of an image where info was blanked out that does not seem to be a security concern?

Here's an example:

https://github.com/dotnet/AspNetDocs/pull/931/files#diff-8833eab4032fe7b69d000aa9b6043f12bbed800b131b1baf5e0676622926021f

The table name for user data is not a secret, and you need to know it to work with user data. It's mentioned several times in [the article text](https://learn.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity#create-an-aspnet-web-app). And notice that it's still available in the revised image as part of the key name.

**Comment by wadepickett** [comment]
I am going back through each of them, thanks for the example!

**Comment by wadepickett** [comment]
@tdykstra, I pulled out or redid some images based on your feedback.  I re-reviewed each one.  The changes of what was reverted is in comit https://github.com/dotnet/AspNetDocs/pull/931/commits/9f625be282f23ba3f24f5a2dbd11d944f1121a02

Also I removed from this PR the images with issues for Real World Cloud Apps.  I will retire the 17 topic Real World Cloud Apps in a separate new PR after this one is merged.

Resetting for a review request, thanks again for the help.

**Review by tdykstra — APPROVED** [review]
LGTM, no reservations about it this time 😄

**Pull request merged**
