### PR TITLE
SP 1887833 aspnet introducing nerddinner tutorial

### PR DESCRIPTION
**Pull request by Shiny11A**

### CODE REVIEW

**Comment by Shiny11A** [comment]
This PR is under Internal review and Peer review now. It is not up for FTE review please. Thanks.

**Comment by Shiny11A** [comment]
This PR is up for FTE review now. Thanks.

**Comment by Shiny11A** [comment]
Hi @Rick-Anderson, kindly FTE review this PR. Thanks.

**Review by Rick-Anderson — CHANGES_REQUESTED** [review]
Revert image changes. In many cases your copy/paste has the wrong image. Why are you changing the images?

**Pull request closed without merging**
