### PR TITLE
Update WebPrefixStrip.config

### PR DESCRIPTION
**Pull request by philipwolfe**
This file is to demonstrate prefix stripping, however there were no prefixes to strip.

`@Rick-Anderson  edit:`
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/config-builder?branch=pr-en-us-352)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@StephenMolloy please review.

**Comment by StephenMolloy** [comment]
In 'Greedy' mode, the prefix is used to filter the config data source before looking at the config file. Then the prefix is stripped from the source data and matched against what is in the config file. So these edits don't make sense.

The original example isn't super good about highlighting this either. Perhaps these edits along with a switch to 'Strict' mode would be more helpful?

**Comment by philipwolfe** [comment]
I had to read the doc 3 times, and I agree that the edits don't make sense.  I do want to ask about how you used Greedy in your comment.  That's not how I understood it from the doc.  With how I understand it now, Greedy wouldn't be needed (here)[https://docs.microsoft.com/en-us/aspnet/config-builder#prefix-handling] but Strict would work just fine because it is a Source for Destination swap.  The prefix attribute wouldn't even be needed when using Strict.  Where I got confused is that the prefix is stripped from the source when values are being mapped.  I don't think there is a good example of Greedy on the whole page because the greedy definition says it will pull all key/value pairs from the external source into the config section.  I like that the examples have great detail.  I think a matrix of when to use the combination of mode and prefix and stripprefix might help a bunch and hilighting the part that I missed about the prefix being removed from the source.  Thoughts?

**Comment by StephenMolloy** [comment]
The details of how this all works in the implementation are just that, implementation details. But the rough idea is this. Lets say we have a config source with the following two pairs:
```
key1     == valueA
pfx_key1 == valueB
```
Then lets say your config has this appSettings section:
```xml
<appSettings>
    <add key="key1" value="ToBeReplaced" />
</appSettings>
```

In **Strict mode with no prefix handling**, the mapping is simple and you end up with `key1 == valueA`.

In **Strict mode with a `prefix="pfx_"`**, then you get `key1 == ToBeReplaced`.  Because 'key1' in the config file does not start with the correct prefix, we don't even bother to look for a value in the config source. If we looked to the source for "pfx_key1" and found a value, it wouldn't make any sense to plug that in to the existing value for "key1" because the two keys don't match and we aren't stripping anything. We also wouldn't insert it as a second appSetting because we're in Strict mode, not Greedy.

In **Strict mode with `prefix="pfx_"` and stripPrefix enabled**, you would get `key1 == valueB`. In this case we see "key1", prepend the prefix and go search the source for "pfx_key1". We find that value and come back and put it in the "key1" appSetting. It works like this because this was the original intended scenario for prefixes and stripping... to allow pulling a subset of values from a config source while not requiring the config file to look bloated and ugly. Ie, apps can pull appSettings from the environment as well as connection strings and not pull in any of the other junk floating in the set of environment variables, but they wouldn't have to name all their connection strings "CS_*" in order to make it work.


In **Greedy mode with no prefix handling**, the mapping is simple and you get two appSettings: `key1 == valueA` and `pfx_key1 == valueB`.

In **Greedy mode with `prefix="pfx_"`**, then you still get two appSettings: `key1 == ToBeReplaced` and `pfx_key1 == valueB`. This happens because, as with Strict mode, we are only interested in updating config values that start with the prefix. Unlike Strict mode though, we do have the ability to add new appSettings, so we go ask the config source for everything that starts with "pfx_" and either update in place or add a new setting.

In **Greedy mode with `prefix="pfx_"` and stripPrefix enabled**, you would only get one appSetting: `key1 == valueB` This is because we do the same thing as above - go and ask the source for all settings that start with the prefix - but then we strip the prefix and update "key1" since its already there.


One last note, you mentioned above something about not even needing a prefix in Strict mode because it's a simple source/dest swap. I think I understand what you're saying, and that is obviously the simplest use case for config builders. But not using a prefix means you need to be careful if you're using the same truth source for multiple config builders or config sections. Prefixes help keep concerns separate. Some config sources flow that way naturally. Some - like Environment variables - do not. If you need to use prefixes to separate concerns, then you might also want to keep the prefixes out of your config file. You probably have EF or ADO.Net code that creates data sources from a connection string name... and you don't want to update all your code to prefix "CS_" at the beginning of your connection string names in code.

And obviously `stripPrefix` makes no sense if there isn't a prefix specified. (Although we don't actually flag that as an error. We just proceed as if the prefix was "".)

**Comment by Rick-Anderson** [comment]
@philipwolfe  this was fixed. I added a link  in the article
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Rick-Anderson** [comment]
@StephenMolloy  let me know if you'd like me to add your response to [Configuration builders for ASP.NET](https://docs.microsoft.com/en-us/aspnet/config-builder)

**Pull request closed without merging**
