### PR TITLE
Fixes MicrosoftDocs/feedback#3105

### PR DESCRIPTION
**Pull request by JasonWHowell**
Fixing HTML rendering problem as reported by https://github.com/MicrosoftDocs/feedback/issues/3105

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@JasonWHowell  thanks, that fixes it.

**Comment by JasonWHowell** [comment]
@Rick-Anderson I didn't see the preview. Did it work?

**Comment by Rick-Anderson** [comment]
Yes, I looked at the previews

**Comment by Rick-Anderson** [comment]
Merged to live so changes will be visible in a few minutes.

**Pull request merged**
