### PR TITLE
Fix code error in overriding SendAsync

### PR DESCRIPTION
**Pull request by strimpak**
Instead of "protected async override" it should be "protected override async"

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
`protected override Task<HttpResponseMessage> SendAsync(` is used 5 time in [this document](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers#custom-message-handlers)

Are these all wrong? @strimpak  Can you post a sample I can test?

**Comment by Rick-Anderson** [comment]
@strimpak [this doc](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers#custom-message-handlers) uses ` protected override async Task<HttpResponseMessage> SendAsync(` but uses `async` inconsistently.

I'm sure when Mike wrote these they all compiled. @scottaddie  please comment.

**Comment by Rick-Anderson** [comment]
@tugberkugurlu in your [Dealing with Asynchrony inside the ASP.NET Web API HTTP Message Handlers](https://www.tugberkugurlu.com/archive/dealing-with-asynchrony-inside-the-asp-net-web-api-http-message-handlers) blog, you don't use `async`. I'm guessing that's the correct approach.

**Comment by scottaddie** [comment]
@Rick-Anderson Either form is fine, but we should be consistent all throughout. If you want an example, check out the Kestrel code used in ASP.NET Core: https://github.com/dotnet/aspnetcore/blob/7a0e7fef3b4d32a42a014e6de2652034a37952f5/src/Servers/Kestrel/Core/src/Middleware/Internal/LoggingStream.cs#L94-L106

**Comment by Rick-Anderson** [comment]
@scottaddie  in https://github.com/dotnet/aspnetcore/blob/7a0e7fef3b4d32a42a014e6de2652034a37952f5/src/Servers/Kestrel/Core/src/Middleware/Internal/LoggingStream.cs#L94-L106

Why do they switch order of `async override` to `override async` 

```
public async override Task<int> ReadAsync(
public override async ValueTask<int> ReadAsync(
```

**Pull request closed without merging**
