### PR TITLE
Typo "udpate"→"update"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://learn.microsoft.com/en-us/aspnet/signalr/overview/older-versions/tutorial-server-broadcast-with-aspnet-signalr 
https://github.com/dotnet/AspNetDocs/blob/main/aspnet/signalr/overview/older-versions/tutorial-server-broadcast-with-aspnet-signalr/samples/sample4.cs 
#PingMSFTDocs

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

**Comment by hyoshioka0128** [comment]
@Rick-Anderson - Question: It says [3rd of next month] on February 22nd, and I checked the next month (=March 2023) and the month after next (=April 2023), but my name was not listed in the Community contributors section.

[ASP.NET Core docs: What's new for March 2023](https://learn.microsoft.com/en-us/aspnet/core/whats-new/dotnet-aspnetcore.docs-mod3)
image

[ASP.NET Core docs: What's new for April 2023](https://learn.microsoft.com/en-us/aspnet/core/whats-new/dotnet-aspnetcore.docs-mod4)
image

**Comment by Rick-Anderson** [comment]
@hyoshioka0128  that's strange. 
[ is:pr is:closed author:hyoshioka0128](https://github.com/dotnet/AspNetCore.Docs/pulls?q=+is%3Apr+is%3Aclosed+author%3Ahyoshioka0128+) shows 0 PR's, so that's why our bot wouldn't generate an entry.

cc @tdykstra  @guardrex  in case they have any ideas.

**Comment by Rick-Anderson** [comment]
OK, I figured it out. Sorry I left that comment. That's only for PR's in the https://github.com/dotnet/AspNetCore.Docs, it doesn't apply to this repo.

**Comment by hyoshioka0128** [comment]
@Rick-Anderson - I figured it out myself after reading your reply.
Thank you for taking the time to investigate.
It's okay if you mark it as Closed.

**Pull request merged**
