### PR TITLE
Fix malformed known anchor in system-web-samesite

### PR DESCRIPTION
**Pull request by jeremycook**

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@jeremycook  how did you find that?

**Comment by jeremycook** [comment]
@Rick-Anderson that there was a broken link was pretty obvious when looking at the page.

image

**Comment by Rick-Anderson** [comment]
Thanks again.

**Comment by jeremycook** [comment]
You're welcome. Thank you to you and your team for the docs.

**Pull request merged**
