### PR TITLE
Update Azure URL

### PR DESCRIPTION
**Pull request by mairaw**
/cc @BethMassi - this round of updates is for ASP.NET Framework docs. Also has links with different params.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  can you fix the links?

**Comment by mairaw** [comment]
I'll change that now. Sorry about that!

**Comment by mairaw** [comment]
Done!

**Comment by scottaddie** [comment]
Thanks for the PR, @mairaw!

**Pull request merged**
